---
title: "GAI vignette"
output: rmarkdown::html_vignette
extra_dependencies: ["xcolor", "hyperref"]
vignette: >
  %\VignetteIndexEntry{vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Introduction to the GAI package

The GAI package is an extension of functionality provided by 
\href{https://onlinelibrary.wiley.com/doi/full/10.1111/biom.12506}{Dennis
\textit{et al} (2016)}. The package provides a user interface for calculating a Generalised Abundance Index
(GAI) for seasonal invertebrates, with multiple options for covariate inclusion,
seasonal flight patterns and observed count distributions, along with the
ability to conduct bootstraps to obtain measures uncertainty for estimated
parameter and GAI values.

This vignette will illustrate the features available within the package by 
providing an example workflow on simulated data.

# Installing the Package from Source

In order to install the GAI package from source, the folder containing the
source code must be downloaded from Github: https://github.com/calliste-fagard-jenkin/butterflyCode

```{R loading, results = 'hide', warning = F}
#install.packages('devtools')
library(devtools, quietly = T)
install_github("calliste-fagard-jenkin/GAI", quiet = T)
library(GAI)
```

# Preparing Data for the GAI Package

Let us begin by loading an example data set which is provided within the GAI
package, and examining its structure. These data consist of a simulation from 
a mixture model with three broods, across 50 sites and 26 occasions (one survey
every week from April to September, inclusive, for a given year).

```{R data, fig.width = 7, fig.height = 5}
# For the pipe operator:
library(magrittr)
data("example_data")
head(example_data)

# The GAI package comes with a handy function to convert data.frame data to 
# a matrix of counts, to facilitate plotting. This function also checks if 
# the survey has any missing occasions, so can be a useful way of sanitising
# a new dataset:
test_data <- extract_counts(example_data, returnDF = F)

# Plot the observed densities, averaged across all sites:
test_data %>% apply(2, mean, na.rm = T) %>% 
  plot(x = 1:ncol(test_data), type = 'l', col = rgb(1, 0, 0, 0.6), lty = 2, 
       xlab = 'Week', ylab = 'Observed count, averaged across all sites')
```

Each row in our input data.frame is used to store the result of the observed 
count at a given site on a given occasion. We assume that the interval between
each occasion is fixed, and that sites are independent. The 'site', 'occasion'
and 'count' columns must be given these precise names to allow the GAI package 
to recognise them. Missing observations can be listed with an NA entry.

Sites and occasions can have either character or numeric names.  Because 
of this, the GAI package will assume occasions occured in the order they first
appear in the data frame. If no observations were collected for any sites on a
given occasion, this occasion should still be included in the data.frame with 
NA entries for each site.

The fourth column 'altitude' represents a covariate (with standardised values),
and will be used to illustrate how covariates can be included into different
models available within the package. 

# Fitting a Simple Model

As described by
\href{https://onlinelibrary.wiley.com/doi/full/10.1111/biom.12506}{Dennis
\textit{et al} (2016)}, the Generalised Abundance Index is a model
comprised of two parts. Firstly, the seasonal flight pattern  describes the
density of arrivals at each occasion in the study, and can be modelled either by 
a stopover model \textcolor{red}{cite Matechou et al 2014}, a spline, or an
n-component mixture model. The choice of seasonal flight pattern can be
specified using the options "stopover", "spline" and "mixture", for each of the
above options, respectively.

The second part of the GAI model describes the distribution of observed counts
of individuals at each site on a given occasion. The package includes Poisson
("P"), Negative Binomial ("NB") and Zero-Inflated Poisson ("ZIP") as options
for this distribution.

```{R fitting}
# We can load the true parameter values of the simulated data set from the 
# GAI package, to more easily find starting parameter values for this example:
data("example_par")

# The 'options' argument of the fit_GAI function is how we specify the 
# specific model we'd like the package to fit. For mixture and stopover models
# we can specify if each brood should be modelled to have the same standard 
# deviation, and the number of broods our model should use:
my_options <- list(B = 3, shared_sigma = T)

# In the case of a spline-based model, the package needs to know the number of
# degrees of freedom and the degree of the splines we want to use:
options_for_splines <- list(df = 20, degree = 3)

# The fit_GAI function includes a 'verbose'  option, which prints the value of
# the negative log-likelihood at each iteration, and also the option to 
# estimate the hessian matrix of the parameters, to obtain their 
# variance covariance matrix:
my_mixture_GAI <- fit_GAI(start = example_par,
                          DF = example_data, a_choice = "mixture",
                          dist_choice = "ZIP", options = my_options,
                          verbose = T, hessian = T)

# Print the MLEs to show the model has fitted correctly:
my_mixture_GAI$par

# Not forgetting to add degrees of freedom and degree of splines information,
# and noting that specifying the number of broods will no longer have an 
# effect:
my_spline_GAI <- fit_GAI(start = rep(0, 20), DF = example_data,
                         a_choice = "splines", dist_choice = "P",
                         options = options_for_splines, verbose = T,
                         hessian = T)

# Print the MLEs to show the model has fitted correctly:
my_spline_GAI$par
```
If an incorrect number of starting values is given to fit_GAI, an error will 
be raised, and a printout will indicate the parameter starting values that
fit_GAI expects. The order of these starting values is important, and matches 
the order of the output fit_GAI produces in this scenario. This feature should
be used to avoid making mistakes when unsure of how many parameters a model
specification will require. Confusingly, NA values are not allowed as starting
values, but functionality exists within the code to aid in finding reasonable
starting values, which is outlined later in this vignette.

It's worth noting that multiple numerical methods exist for finding the MLEs 
of the GAI model. The package uses the 'optim' function which makes use of the 
"Nelder-Mead" algorithm by default, but this can be changed to other options,
such as "BFGS" or "SANN" (simulated annealing) by passing in method = "SANN"
(for example) as an argument to fit_GAI.

\textcolor{red}{But not yet...}
```{R mistake}
# We cut off some of our starting parameters on purpose, to cause the exception
# to be raised:
try({my_mixture_GAI <- fit_GAI(start = example_par[1:3], DF = example_data,
                               a_choice = "mixture", dist_choice = "ZIP",
                               options = my_options, verbose = T,
                               hessian = T)}, silent = T)
```

# Including Covariates

Models using 'mixture' and 'stopover' seasonal flight patterns are able to
include covoariates on the values of the means, disperisions and weights for
their normal distribution components.

Covariates can be included either as a general formula, which will apply to 
all broods, or be specified individually for each brood. Covariates for the
normal components should be specified by adding a 'mu_formula',
'sigma_formula', or 'w_formula' to the 'options argument', for the mean,
standard deviation, and for weights of each component, respectively.

When specifying covariate formulae one by one for each brood, we have the option
of giving completely different formulae for each brood, or using NULL to specify that no covariates should be fitted for a given brood. Because of this 
flexibility, it is good practice to ensure the list of formulae always has
the same number of elements as the number of broods specified. If more formulae
are specified than there are broods, these extra formulae will simply be
ignored.

```{R covariates}
# To specify a formula which will be identical for each brood, 
general_options <- list(B = 3, shared_sigma = T,
                        mu_formula = formula(~altitude))

# To be able to fit brood-specific covariate options for the standard deviations
# we require the standard deviation to be estimated individually for each brood,
# and so we set shared_sigma = F.
brood_specific_options <- list(B = 3, shared_sigma = F, 
                               sigma_formula =
                                 list(NULL,                     # for brood 1
                                      formula(~altitude),       # for brood 2
                                      formula(~I(altitude^2)))) # for brood 3

# The distributional parameter we had previously for the ZIP (Zero-Inflated 
# Poisson) distribution will disappear now that we're fitting a simple 
# Poisson. However, we are also adding a covariate formula which will require
# one additional parameter. We'll give this a starting value of 0, which 
# reflects an a priori belief that the covariate has no effect. To do this, 
# we simply replace the final value of example par with 0, since distributional
# parameters are placed at the end of the parameter vector, and covariate are 
# placed after these, when they are present:
general_fit_start <- example_par[1:(length(example_par) - 1)] %>% c(0)

# Having specified our covariate formulae, we can fit the model in exactly the
# same way as before:
general_fit <- fit_GAI(start = general_fit_start, DF = example_data,
                       a_choice = "mixture", dist_choice = "P",
                       options = general_options, hessian = T)

# Because these covariate data are dummies, we expect the fitted value to be
# very close to zero:
general_fit$par

# To make the starting values for the new model, we steal the known values from 
# the example_par vector (using the shared standard deviation across broods as
# the estimate for each brood individually). We then also add two 0s as our 
# starting values for the covariate parameters
brood_specific_start = c(example_par[c(1:3, rep(4, 3), 5:6)], rep(0, 2))
brood_specific_fit <- fit_GAI(start = brood_specific_start,
                              DF = example_data, a_choice = "mixture",
                              dist_choice = "P", hessian = T,
                              options = brood_specific_options)
# Checking the MLEs:
brood_specific_fit$par
```

It should be noted that the GAI package comes with no methods for interpolating 
missing covariate values. Because of this, any NA covariate values in data.frame
objects passed to fit_GAI will cause an error to be outputted to the console. 
The GAI package only supports 'spatial' covariates, that is, covariates whose 
values vary only by site, and are identical for every single sampling occasion, 
for a given site. Supplying time-varying covariates to fit_GAI will similarly
lead to an error being thrown.

```{R covErrors}
example_NA <- example_time_varying <- example_data

# Turn roughly 5% of our altitude data to NA values:
indices <- example_NA$altitude %>% length %>% rbinom(size = 1, prob = 0.05)
example_NA$altitude[indices %>% as.logical] <- NA

# Turn our altitude data into a time-varying covariate by making it a function 
# of the occasion:
example_time_varying$altitude <- example_data$altitude * example_data$occasion

# Trying to fit a covariate model with these new data will throw the relevant
# errors:
error_fit <- try(fit_GAI(start = general_fit_start, DF = example_NA,
                         a_choice = "mixture", dist_choice = "P",
                         options = general_options, hessian = T))

# Trying to fit with a time-varying formula: 
error_fit <- try(fit_GAI(start = general_fit_start, DF = example_time_varying,
                         a_choice = "mixture", dist_choice = "P",
                         options = general_options, hessian = T))

```

# Finding Starting Values

To aid numerical routines in estimating the maximum likelihood estimates of
parameter values, link functions are used to ensure that parameter guesses can
always be made on the entire real line. Because many broods can be used, the GAI
package uses custom link functions for mean arrival times and dispersions, which
are slightly more complicated that the typical log and logistic link functions.

The fit_GAI function expects all starting values to be given on this link scale, 
which can make using our intuition or knowledge of our data very difficult to 
produce good starting values. To remedy this, the transform_starting_values
function can be used to transform parameter guesses on the 'real world' scale to 
the link scale.

```{R transform1, fig.width = 7, fig.height = 5}
# Let's produce a slightly 'annotated' version of the plot of observed counts
# we had before. We'll add in some lines where we think the mean brood arrival
# times are, and add in horizontal lines to try to estimate thw standard 
# deviation of each brood's arrivals:
test_data %>% apply(2, mean, na.rm = T) %>% 
  plot(x = 1:ncol(test_data), type = 'l', col = rgb(1, 0, 0, 0.6), lty = 2, 
       xlab = 'Week', ylab = 'Observed count, averaged across all sites')

plot.col <- 'blue'
plot.base <- 1

# Mean brood arrival lines:
lines(rep(4.1, 2), c(plot.base, 4.6), col = plot.col)
lines(rep(13.0, 2), c(plot.base, 21.3), col = plot.col)
lines(rep(23.0, 2), c(plot.base, 8), col = plot.col) 

# Mean brood dispersion lines:
lines(c(1, 7.5), rep(plot.base, 2), col = plot.col)
lines(c(9, 18), rep(plot.base, 2), col = plot.col)
lines(c(19, 26), rep(plot.base, 2), col = plot.col)

# The length of the three horizontal bars that measure the width of our broods:
brood_widths <- c(6.5, 9, 7)

# Using a very rough rule of thumb that 95% of data in a normal distribution are
# found within 1.96 standard deviations from the means, we use the half width of
# our bars as an estimate of two sigma:
sigma_guesses <- brood_widths / 4

# Our guesses for the means can simply be read off of the lines of code that
# produced the plot:
mu_guesses <- c(4.1, 13, 23)

# To guess the weights, we make the crude assumption that the height of the peak
# of a brood relative to the others is roughly propoprtional to the percentage
# of the population that finds itself in this brood:
w_guesses <- c(4.6 - plot.base, 21.3 - plot.base, 8 - plot.base) %>%
  sum_to_one
```


Let's consider our brood_specific_fit once more, but using the 
transform_starting_values function to obtain better starting values, without
knowing the distribution our data came from. The transform_starting_values 
function will assume that 0 is a reasonable starting value for all covariate
parameters and spline parameters, which usually leads to numerically sound
estimation of the MLEs. However, if covariates aren't normalised, and have 
large magnitude, this won't be the case.

```{R transform2}
# We create a list of starting values for parameters with the same structure 
# as the options argument for fit_GAI:
my_starting_guesses <- list(mu = mu_guesses, sigma = sigma_guesses,
                            w = w_guesses)

# Note: When a ZIP or NB model is used, we can also include a guess for the
# distributional parameter by adding in a dist.par entry to this list, and 
# additionally a retention probability 'phi' can be added for stopover models 
new_brood_specific_start <-
  transform_starting_values(starting_values = my_starting_guesses,
                            a_choice = "mixture", dist_choice = "P",
                            options = brood_specific_options,
                            # When covariates are included in the model, we 
                            # need to include the data.frame of observations and
                            # covariate values, or the GAI package won't be able
                            # to figure out how many parameters the model 
                            # specification requires. This can be omitted for
                            # non-covariate-including models
                            DF = example_data)

# Let's print these new starting values, and refit the model:
print(new_brood_specific_start)
new_brood_specific_fit <- fit_GAI(start = new_brood_specific_start,
                                  DF = example_data, a_choice = "mixture",
                                  dist_choice = "P", hessian = T,
                                  options = brood_specific_options)
# Checking the MLEs:
new_brood_specific_fit$par
```

# Using Bootstraps

Bootstraps in the GAI package are available in two options. The first option
will resample sites (and their covariate values) from the observed data set, 
refitting the model each time it does this. It then extracts the bootstrap
distribution of estimated site superpopulation sizes and parameter estimates to
create a quantile method confidence interval for these. Because this type of
bootstrap can be incredibly computionally expensive, functionality has been 
provided to do these calculations in parallel.

The second method of bootstrapping involves resampling parameter values from
their asymptotic multivariate normal distribution. This involves a numerical 
estimate of the Information matrix, and so is only available if a model has
been fitted with the hessian = TRUE option in fit_GAI.

The second type of bootstrap runs considerably faster, and is likely to be the 
only available option when many sites or covariates have been included, due to
computational constrains. However, it should be noted that the first type 
typically produces intervals with coverage closer to the target, as it has
no dependence on asymptotic properties or estimates of the Information matrix.

\textcolor{red}{Reminder to myself to parallelise MLE resampling bootstrap}

```{R bootstrap, warnings = F}
# To produce a bootstrap, we must specify if we wish to refit the model
# (determining the type of bootstrap fitted), as well as the number of
# bootstrap resamples we would like to use (R):
general_fit_bootstrap <- bootstrap(general_fit, R = 1000, refit = F,
                                   alpha = 0.01)

# The more time-consuming bootstrap can be fitted in parallel, with a chosen
# number of cores. If this is not specified, the default number of cores 
# will be one less than the number available on the computer, so this must
# always be specifed if running models on a large server:
refitting_bootstrap <- bootstrap(general_fit, R = 10, refit = T, parallel = T,
                                 cores = 3, alpha = 0.01)
```


The bootstraps output contains raw values from each iteration of the estimated
parameter values, the flight path densities for each site and occasioon, the estimated site totals (site superpopulations), and the average estimated site
total. The $1 - \alpha$ confidence intervals are available in the \$par,
\$sites and \$index elements of the bootstrap output for the parameters,
individual site totals and average site total, respectively:

```{R intervals}
# Taking a look at the results of the 'refit the model at each iteration'
# style of bootstrap:
refitting_bootstrap$par

```

# Model Outputs

The GAI package comes with some simple functionality for summarising models, 
as well as more detailed outputs, which will be covered in more detail. The 
standard R 'summary' function can be used to see the model's AIC, average 
estimate site total across all sites, and also the MLEs for all model 
parameters.

```{R summary}
# Get a basic summary of the model outputs:
summary(my_mixture_GAI)

# We can also obtain the AIC on its own using the standard AIC R function if 
# we aren't interested in producing the rest of the summary:
AIC(my_mixture_GAI)
```

The output of the fit_GAI function is a list with a few important elements.
The 'par' element gives named estimates of the MLEs for the model parameters, 
with 'value' giving the value of the negative log likelihood
evaluated at the MLEs. 'counts', 'convergence', 'message' and 'hessian' are all
standard outputs given by the optim function with details on the numerical 
process of estimating the MLEs. 'spline_specs' contains the user-specified
options for fitting splines, and will be an empty list for mixture and 
stopover models. 'dist_choice' and 'a_choice' contain the count distribution 
and flight path distributions, respectively. Skeleton contains the skeleton
list of parameter values that the package uses to fit the model, with 
'options' being the list of options passed to fit_GAI. 'maxiter' refers to the
maximum number of iterations used to estimate the MLEs of ZIP and NB models. 'A'
and 'N' contain the matrix of estimated seasonal densities at each site and 
occasion, and the vector of estimated site totals, respectively. 'DMs' contains
the list of design matrices used by the GAI package to include the selected
covariate formulas in the model. 'obs' contains the count observations in 
matrix form, with sites as rows and occasions as columns. This is the same
format as for 'A'. 'DF' contains the original data.frame supplied to fit_GAI,
and finally, 'tol' specififies the stopping condition used for the model (an 
epsilon such that during an iterative process for fitting a ZIP or NB model, 
a difference of less than epsilon in the negative log likelihood between two
iterations causes the process to terminate).

# Transforming Parameter Estimates

Numerical solvers that attempt to find the MLEs must be able to perform guesses
anywhere on the real scale. This causes issues with certain parameters which 
can only take on values in very particular ranges, such as probabilities which
must always be between 0 and 1, for example. Further to this, the estimation 
of values such as mean arrival times for broods can be unidentifiable if 
specified ambiguously. In this example, unless we force the mean for the second
brood to be greater than that for the first (and so forth), then multiple sets
of parameters could give the same maximal value of the log likelihood. For
these reasons, the GAI package uses link functions to map between the real line
on which we make parameter value guesses during fitting, and the 'parameter
space line', where all parameters are within the correct bounds.

In order to be able to interpret our output values, we must apply the relevant
link functions to transform them back to the appropriate scale. For mu
parameters this can be done with the means_link function. For standard
deviations, a log-link is used, and so fitted values should be exponentiated.
Weights also use a custom link function, which can be applied to fitted values
using the probs_link function. The extra distributional parameter for the ZIP
uses a logistic link (by virtue of being a probability), which can be applied
with the qlogis function, whereas the rate parameter for an NB model should
be exponentiated, to ensure it is always positive.

```{R backtransform}
# The easiest way to obtain transformed parameter values on the correct scale
# is to use the transform_output function. This function uses the skeleton and
# options present in the fitted model object to apply covariate formulas before
# applying link functions.
DF_to_transform <- data.frame(altitude = c(-10, 0, 10))
transform_output(brood_specific_fit, DF_to_transform)

# It's important to include all covariates exactly as they were named in the 
# call to fit_GAI, otherwise an error will be thrown, giving the name of the 
# missing covariate.
try(transform_output(brood_specific_fit, data.frame(altiitude = c(-10, 0, 10))))

# NA covariate values will throw an error, as always:
try(transform_output(brood_specific_fit, data.frame(altitude = c(NA, 0, 10))))
```

# Plotting Fitted Curves

The standard R plot function can be used to produce simple plots of the flight 
path of a fitted model. Optionally, either the flight path for each site can 
be included as a separate curve on the same graph, or a smooth can be plotted
instead. This smooth averages through the different values observed at each 
site, at a set of quantiles that can be specified by the user. The default 
behaviour produces plots for the median density ocross sites for a given
occasion, as well as the 5th and 95th quantiles for flight path density. 

To better compare the relative abundance at each site throughout the year, 
especially when covariates have been included in the model, it can be useful to 
scale the flight path curve of each site by the estimated site total. This can 
be done by setting scale_by_N = TRUE in the call to the 'plot' function.

If custom colours are to be used by the plotting function, the colour palette 
can be passed to the 'plot' function as a vector of integers or character colour 
hex values using the 'colours' argument.

```{R plotting, fig.width = 7, fig.height = 5}
colours <- c("#33FFF9", "#33A8FF", "#4233FF")

# The default behaviour will use quantiles = c(0.05, 0.5, 0.95), and therefore 
# will not plot all sites individually. It will also use the standard R base
# graphics colours. The shiftt parameter can be used to shift the legends if 
# the default value places them incorrectly:
plot(general_fit, scale_by_N = T, colours = colours,
     quantiles = c(0.1, 0.5, 0.9), shift = c(-0.45, 0.5))
```