# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stopover_for_loop <- function(betas, phi) {
    .Call('_rGAI_stopover_for_loop', PACKAGE = 'rGAI', betas, phi)
}

weightedSelection <- function(x, probs) {
    .Call('_rGAI_weightedSelection', PACKAGE = 'rGAI', x, probs)
}

