# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

probs_link <- function(x) {
    .Call('_GAI_probs_link', PACKAGE = 'GAI', x)
}

vector_to_counts <- function(x, breaks) {
    .Call('_GAI_vector_to_counts', PACKAGE = 'GAI', x, breaks)
}

#' Rescale a numeric vector so that its entries sum to one
#' 
#' @param x A numeric vector.
#' @export
sum_to_one <- function(x) {
    .Call('_GAI_sum_to_one', PACKAGE = 'GAI', x)
}

stopover_for_loop <- function(betas, phi) {
    .Call('_GAI_stopover_for_loop', PACKAGE = 'GAI', betas, phi)
}

means_link <- function(means) {
    .Call('_GAI_means_link', PACKAGE = 'GAI', means)
}

weightedSelection <- function(x, probs) {
    .Call('_GAI_weightedSelection', PACKAGE = 'GAI', x, probs)
}

rcpp_hello_world <- function() {
    .Call('_GAI_rcpp_hello_world', PACKAGE = 'GAI')
}

